### PR TITLE
only add colonists in workforce to the specialist labels

### PR DESCRIPTION
**Pull request by alexanderabramov**
In base game UI, specializations report is the only way to see at a glance which specialists you globally need to import from Earth, but it includes people outside of workforce who cannot work anyway.

This PR adds a new function Colonist:IsInWorkforce that filters out people who are permanently unable to work due to traits, and ensures City.labels[spec] only includes such people. If a colonist re-enters the workforce due to tech or losing "Tourist" trait, he is re-added to the labels.

### CODE REVIEW

**Comment by Draco18s** [comment]
Are they planning to support PR into the base game code? I figured this was just a reference repository.

**Comment by UberWaffe** [comment]
@Draco18s It is, but providing working code along with your request for a feature is orders of magnitude more likely to get implemented than just a request.
Or at least that is what I think.

**Comment by ivanassen** [comment]
Thank you for the PR - please keep them coming. While we currently don't intend to merge them into the reference repository - it is an old branch corresponding to the last patch released - we will certainly read and consider them all for applying to the base game code.

**Comment by Draco18s** [comment]
@ivanassen: good to know. Just made my own PR to fix something *I'd* noticed.

**Pull request closed without merging**
